# Generated by Django 4.0.1 on 2022-04-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
